web:
  image:
    repository: ghcr.io/104corp/bitnami/nginx
    tag: 1.24.0
  corp104Configs:
    - name: nginx.conf
      value: |
        user www-data;
        worker_processes auto;
        worker_rlimit_nofile 204800;
        error_log  /opt/bitnami/nginx/logs/error.log error;
        events {
          accept_mutex on;
          accept_mutex_delay 500ms;
          worker_connections 1024;
        }
        http {
          include       mime.types;
          default_type  application/octet-stream;
          include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
        # HTTP Server
          server {
            include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
          }
        }
      mountPath: /opt/bitnami/nginx/conf/nginx.conf
    - name: 3267.conf
      value: |
          listen *:8080;
          server_name nginx-3267.104-dev.com.tw;
          index  index.html index.htm index.php;
          location / {
            index     index.html index.htm index.php;
            autoindex off;
            error_page 404 403 500 502 503 504 /syserr.html;
          }
          location /tool {
              proxy_pass http://127.0.0.1:8081;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      mountPath: /opt/bitnami/nginx/conf/bitnami/3267.conf
  
  extraContainers:
    - name: nodejs
      image:
        repository: ghcr.io/104corp/nodejs
        tag: v5
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      ports:
      - containerPort: 8081
        protocol: TCP
        name: nodejs
      readinessProbe: # 偵測應用程式是否 ready
        enabled: true
        initialDelaySeconds: 5  # 延遲開始確認時間
        periodSeconds: 60       # 每 N 秒打一次
        timeoutSeconds: 5       # N 秒逾時
        successThreshold: 1     # 若成功回應一次就算本次成功
        failureThreshold: 3     # 重試三次後才算失敗
        httpGet:
          path: /
          port: 8081
      livenessProbe: # 偵測應用程式是否正常運行
        enabled: true
        initialDelaySeconds: 5  # 延遲開始確認時間
        periodSeconds: 60       # 每 N 秒打一次
        timeoutSeconds: 3       # N 秒逾時
        successThreshold: 1     # 若成功回應一次就算本次成功
        failureThreshold: 3     # 重試三次後才算失敗
        httpGet:
          path: /
          port: 8081
    - name: network-tools
      image: 
        repository: ghcr.io/104corp/network-tools
        tag: v1
      command: ["sh", "-c", "tail -f /dev/null"]
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
